baseURL = "https://yuizho.github.io/blog/"
languageCode = "ja"
title = "J'aime les ramens"
theme = "minos"
hasCJKLanguage = true

[Author]
  name = "yuizho"

[params]
    googleAnalytics = "UA-155195987-1"